135 chronoemulator basic implementation
grc-iit/chronolog pull request #149
Opened 2024-04-11 11:38 UTC by EnekoGonzalez3

Most simple implementation of a ChronoEmulator to simulate how ChronoLog works and be able to develop serving layer components: 

[Sequence Diagram](https://drive.google.com/file/d/1Uf07IsRkWD96RaUhorFGnH_OcafXlu3Q/view?usp=drive_link)

[General Documentation](https://docs.google.com/presentation/d/1yxyKAjDQu8UBg5yQBrF4MUq5bso0dzKkj3Ru9SJxjrs/edit#slide=id.p)

2024-04-24 16:56 UTC, ibrodkin requested changes

2024-04-24 16:56 UTC, ibrodkin commented on Plugins/chronoemulator/src/chronicle.h
> +    std::vector <std::shared_ptr <StoryHandle>> stories; ///< Vector of stories in the Chronicle.
I think that std::vector  is not a good container choice for stories. The overwhelming usage pattern here is lookup of story within the chronicle, while vector is inefficient for random access operations

2024-04-24 16:56 UTC, ibrodkin commented on Plugins/chronoemulator/src/story.h
> +    std::vector <std::pair <uint64_t, std::string>> events; ///< A list of events and their timestamps.
std::vector is not a best choice for the events container. I imagine most of hte emulation would revolve around lookup and retreaval of events based on the timestamp as a key. Key based data structure would be more efficient here

2024-05-01 20:15 UTC, ibrodkin commented on Plugins/chronoemulator/src/chronicle.cpp
> +        return it->second.get();
I think chronolog_client code returns existing story handle in case the story is already acquired

2024-05-01 20:15 UTC, ibrodkin commented on Plugins/chronoemulator/src/chronicle.cpp
>          return 0;
it's safe to return success for the story that's not acquired

2024-05-03 01:59 UTC, EnekoGonzalez3 commented
Updated documentation: 
[Sequence Diagram](https://drive.google.com/drive/folders/1Y3462mzDEgJ1DNiFrS_S6wnsfMOEi3YI)

2024-05-03 15:36 UTC, ibrodkin approved these changes

2024-05-10 21:59 UTC, fkengun reviewed
Comments are left in the slides.
I am not sure if something is missing or it is planned to be a basic version that only consider a single-thread sequential client. The support of concurrent acquisition is missing.
The logic of destroyChronicle() does not check acquisition states of its Stories, which is a separate issue even without considering concurrent acquisition.
We can clearify the requirement of the issue to use the current state plus a fixed destroyChronicle() logic as a first-step milestone. And we add concurrent acquisition support in the next PR.

2024-05-10 22:02 UTC, fkengun requested changes
I forgot to change the default review. Pls check my previous comments for changes.
tldi, acquisition state of its own Stories needs to be checked when destroying a Chronicle.

2024-06-03 16:38 UTC, fkengun approved these changes

2024-06-06 16:50 UTC, merged