127 storychunkextractor using rdma
grc-iit/chronolog pull request #150
Opened 2024-04-15 21:32 UTC by fkengun

Changes:
- New `StoryChunkExtractorRDMA` class extending `StoryChunkExtractorBase`
- Replace `CSVFileStoryChunkExtractor` in Keeper with `StoryChunkExtractorRDMA `to drain StoryChunk to Grapher using `tl::bulk`
- Update `record_story_chunk` in Grapher with corresponding receiving code using `tl::bulk`
- Include separate `tl::bulk`-based StoryChunk transfer test case in `test/integration/Keeper-Grapher`

2024-04-16 16:29 UTC, ibrodkin commented on ChronoKeeper/StoryChunkExtractor.cpp
> +            LOG_DEBUG("[StoryChunkExtractionBase] Story chunk processing returns {}, ES Rank: {}, ULT "
in case processStoryChunk fails the StoryChunk should be pushed back on ExtractionQueue so that it's not lost..

2024-04-16 17:15 UTC, ibrodkin requested changes
PR looks good overall.  Please, see my comments for a few changes that I think would improve serialization time

2024-04-16 17:15 UTC, ibrodkin commented on ChronoKeeper/StoryChunkExtractorRDMA.cpp
> +        char*serialized_buf = new char[MAX_BULK_MEM_SIZE];
serialized buffer should be a member of the Extractor class that is created in the Extractor constructor. I bet that allocation/deallocation of the buffer memory takes up a significant chunk of time you are now attributing to serialization.

2024-04-16 17:15 UTC, ibrodkin commented on ChronoKeeper/StoryChunkExtractor.h
> +    StoryChunkExtractionQueue chunkExtractionQueue;
please, don't forget to move the chunkExtractionQueue back to private

2024-04-16 17:15 UTC, ibrodkin commented on ChronoKeeper/StoryChunkExtractorRDMA.cpp
> +            confManager.KEEPER_CONF.KEEPER_GRAPHER_DRAIN_SERVICE_CONF.RPC_CONF.IP + ":" +
Is there a reason that tl_engine is created outside the Extractor class but tl_provider is created in the constructor. Can the provider be created in the same place as the engine? Seems more intuitive this way

2024-04-16 17:15 UTC, ibrodkin commented on ChronoKeeper/StoryChunkExtractorRDMA.cpp
> +    {
Are we putting a binary archive into a stringstream in order to get the size of the archive ? this also would hurt serialization time

2024-04-16 17:15 UTC, ibrodkin commented on ChronoKeeper/StoryChunkExtractorRDMA.h
> +    uint16_t grapher_service_id{};
It's hard to justify ConfigurationManager instance as a member of StoryChunkExtractorRDMA class. Please,  remove it.

Please, make serialized_buffer a member of StoryChunkExtractorRDMA class

2024-04-16 17:18 UTC, ibrodkin commented on chrono_common/StoryChunk.h
> +#include <thallium/serialization/stl/map.hpp>
thallium/serialization/stl files are already included  in the develop version of StoryChunk.h.  lines 6-8 can be removed .

2024-04-16 17:31 UTC, ibrodkin commented on ChronoGrapher/GrapherRecordingService.h
> +        mem_vec.reserve(MAX_BULK_MEM_SIZE);
does mem_vector need to be local to this function?

2024-04-17 20:13 UTC, fkengun commented on ChronoKeeper/StoryChunkExtractorRDMA.cpp
> +        char*serialized_buf = new char[MAX_BULK_MEM_SIZE];
serialized buffer is moved to member of ExtractorRDMA class. the perf test results have been updated at https://docs.google.com/spreadsheets/d/1waZhOoPa-LnZTETndmM5vManCrc0nBL0C4ddN-XQ7X0/edit#gid=1441574536. the serialization is indeed faster, but not by much.

2024-04-17 20:14 UTC, fkengun commented on ChronoKeeper/StoryChunkExtractorRDMA.cpp
> +            confManager.KEEPER_CONF.KEEPER_GRAPHER_DRAIN_SERVICE_CONF.RPC_CONF.IP + ":" +
both of them are created in `GrapheriInstance.cpp` now

2024-04-17 20:15 UTC, fkengun commented on ChronoGrapher/GrapherRecordingService.h
> +        mem_vec.reserve(MAX_BULK_MEM_SIZE);
mem_vector is moved as a member now. but I think we may need to move it back when we have more than one recording thread.

2024-04-17 20:16 UTC, fkengun commented on ChronoKeeper/StoryChunkExtractorRDMA.cpp
> +        char*serialized_buf = new char[MAX_BULK_MEM_SIZE];
we may need to move it back when we have more than one draining thread

2024-04-24 18:18 UTC, ibrodkin reviewed
Please, wrap the lines that collect performance timing with ifdef DEBUG

2024-04-24 20:37 UTC, ibrodkin approved these changes

2024-04-24 21:18 UTC, merged