160 Add Thread Interdependency Test for ChronoLog Client API
grc-iit/chronolog pull request #190
Opened 2024-09-07 12:08 UTC by EnekoGonzalez3

### Summary:

This PR introduces a thread interdependency test to the ChronoLog correctness testing pipeline. The test ensures that threads perform operations in coordination, relying on shared memory to achieve a consistent global state. The test improves the accuracy of multi-threaded API interactions, ensuring a determined outcome based on the interdependencies between threads.

### Key Changes:

- **Shared State Array**: A shared array for thread states is introduced, protected by a mutex and a condition variable to ensure proper synchronization.
- **Thread State Bitmasking**: Defined bitmask states for each thread operation (initialization, chronicle creation, story acquisition, logging, and destruction).
- **State Updates and Synchronization**: All threads now update the shared state array and wait for all threads to reach specific states before proceeding, ensuring proper order of operations.

### Testing:

- Applied and tested with all multi-threaded client tests (`client_lib_multi_storytellers`, `client_lib_multi_pthread_test`, `client_lib_multi_argobots_test`, `client_lib_hybrid_argobots_test` & `client_lib_multi_openmp_test`) ensuring interdependencies between threads are handled correctly.
- Verified that operations such as chronicle creation, story acquisition, logging, and destruction are synchronized and error-free.

2024-09-12 15:25 UTC, fkengun commented on test/integration/Client/client_lib_multi_storytellers.cpp
> +std::vector <int> shared_state;
These shared global variables, definitions, and functions are better to be put in a header file and included in each test case.

2024-09-12 15:27 UTC, fkengun commented on test/integration/Client/client_lib_multi_storytellers.cpp
> +    FINISHED_LOGGING = 1 << 3, // 00001000 (binary), 8 (decimal)
Better to say `DATA_ACCESS_FINISHED`. Logging could be ambiguous. And we will have Read-after-Write or Write-after-Read test cases in the future.

2024-09-13 15:09 UTC, ibrodkin requested changes
1. The idea of having the array of thread states is about tracking each thread state individually.  I suggest that each thread updates only its own state. This way we know that the only writer on the _shared_state[i]_ element of the array is thread _i_ , every other thread has read only access to _shared_state[i]_ making the mutex unnecessary. 
Please, remove the synchronization mutex.
2. Please use bitmask operations on the bitmask values, this allows for more nuanced state tracking.
3. Please, make use of the sshared state array values to make validation of the return values coming from the visor more nuanced.

2024-09-13 15:09 UTC, ibrodkin commented on test/integration/Client/client_lib_hybrid_argobots_test.cpp
> +{
It's a good practice to leave 0000 for the "zero" state , I would call it "UNKNOWN"

2024-09-13 15:09 UTC, ibrodkin commented on test/integration/Client/client_lib_hybrid_argobots_test.cpp
> +{
I suggest that each thread updates only its own state. This way we know that the only writer on the shared_state[i] is thread i , every other thread has read only access to shared_state[i] making the mutex unnecessary.

2024-09-13 15:09 UTC, ibrodkin commented on test/integration/Client/client_lib_multi_argobots_test.cpp
>                , chronicle_name, ret);
Please, make this paragraph more nuanced based on the state of the other threads.

2024-10-12 00:25 UTC, closed without merging