Client program
grc-iit/chronolog pull request #26
Opened 2023-01-11 21:32 UTC by aparnasasidharan2017

2023-01-11 21:33 UTC, aparnasasidharan2017 commented
Closes #15

2023-01-11 23:11 UTC, fkengun commented
It fails on my local machine. Here is all the output.
`➜  ChronoAdmin git:(dev_latest) ./ChronoAdmin 
 Enter protocol 0 for sockets, 1 for TCP, 2 for verbs 
0
 Enter server hostname (localhost) : 
localhost
 Enter server portnumber (5555) : 
23456
ConfigurationManager.h: initializing configuration with all default values: 
ConfigurationManager.h: RPC_SERVER_IP: 127.0.0.1
ConfigurationManager.h: RPC_BASE_PORT: 5555
ConfigurationManager.h: RPC_NUM_PORTS: 1
ConfigurationManager.h: RPC_NUM_SERVICE_THREADS: 1
ConfigurationManager.h: RPC_CLIENT_PORT: 6666
ConfigurationManager.h: RPC_IMPLEMENTATION (0 for sockets, 1 for TCP, 2 for verbs): 0
ConfigurationManager.h: SOCKETS_CONF: ofi+sockets
ConfigurationManager.h: VERBS_CONF: verbs
ConfigurationManager.h: VERBS_DOMAIN: mlx5_0
ConfigurationManager.h: MEMORY_ALLOCATED: 134217728
ConfigurationManager.h: IS_SERVER: 1
ConfigurationManager.h: MY_SERVER_ID: 0
ConfigurationManager.h: SERVER_LIST_FILE_PATH: /home/kfeng/CLionProjects/ChronoLog_review/ChronoLog/build/Client/ChronoAdmin/server_list
ConfigurationManager.h: SERVER_LIST: 
ConfigurationManager.h: BACKED_FILE_DIR: /dev/shm
RPCClient.h: 9RPCClient constructor is called
rpc.h: ChronoLogRPC constructor is called
rpc.h: generate a new client at ofi+sockets://172.17.0.1:37329
rpc.h: lookup_str: ofi+sockets://127.0.0.1:23456
RPCClient.h: 9RPCClient constructor finishes, object created@0x563e52d7e1a0 in thread PID=818708
RPCClient.h: Connect in ChronoLogAdminRPCProxy at addresss 0x563e52d7e1a0 called in PID=818708, with args: uri=ofi+sockets://127.0.0.1:23456, client_id=U7XqntMv
Function returned HG_NOENTRY
terminate called after throwing an instance of 'thallium::margo_exception'
  what():  [/home/kfeng/CLionProjects/ChronoLog_dev/client_refactor/ChronoLog/external_libs/hcl/dependencies/.spack-env/view/include/thallium/callable_remote_procedure.hpp:117][margo_provider_forward] Function returned HG_NOENTRY
[2]    818708 IOT instruction (core dumped)  ./ChronoAdmin
`

2023-01-12 14:12 UTC, aparnasasidharan2017 commented
That failure is correct behavior. The error message says "HG_N0ENTRY", because there is no server process at localhost, 23456.

2023-01-12 17:46 UTC, ibrodkin commented on Client/ChronoAdmin/client_admin.cpp
> +}
1. I think that having command line options to enter connection parameters would be more useful in than interactive mode.  One should be able to invoke the client from the script as well as command line. For example
 chrono_admin  --h     prints the available options
chrono_admin -h <hostname> -p<port>  -l<chronicle>. connects, checks credentials , lists the stories in the chronicle
2. the client should not crash if the connection fails but should catch the exception, provide the error message and exit the the error.

2023-02-03 18:27 UTC, ibrodkin requested changes
Please, address my commend about client_admin.cpp. The rest of the changes are good.

2023-02-03 18:27 UTC, ibrodkin commented on Client/ChronoAdmin/client_admin.cpp
> +}
@aparnasasidharan2017   you've changed Client Admin code to pass the parameters on the command line instead of interactive mode . But now you assume that the parameters are always passed in the strict predefined order. Please, do not assume this. the parameters can be passed in any order , the only thing that we should require is that key-value pair is always together:   -p{rotocol} {protocol_value}.    , but protocol key-value pair may come before or after the hostname pair, or it can be missed altogether in which case we fallback on default if possible or report the error and exit if we don't have a default.

Also assume that the number of parameters would grow as we add functionality to the Client.

2023-02-03 18:27 UTC, ibrodkin commented on Client/ChronoAdmin/client_admin.cpp
> +
Please, replace this  block with iteration loop over args[] array. The order of the command line arguments should not matter as long as key-value pair is present.  For example:  if( args[i] == "-p{rotocol}" and args[i+1] != end() and args[i+1]=="tcp" )  we have valid protocol and continue

2023-02-06 15:42 UTC, ibrodkin approved these changes
changes look good.

2023-02-07 13:48 UTC, merged