17 decouple conf manager and visor rpc init
grc-iit/chronolog pull request #35
Opened 2023-01-30 21:40 UTC by fkengun

I am still using the global ConfigurationManager object CHRONOLOG_CONF. By default, it is initialized with all default values. The ChronoVisor2 takes an object of ConfigurationManager with all values read from a JSON file in its constructor and copies it to the global CHRONOLOG_CONF. rpc-related stuff is initialized inside init(). It is called after the global CHRONOLOG_CONF is set. Thus, when the rpc reads configurations from CHRONOLOG_CONF, everything is set according to the configuration file.

2023-02-03 18:40 UTC, ibrodkin commented on ChronoAPI/ChronoLog/include/ClocksourceManager.h
Do we need an UNKNOIWN case for Clocksource?  Is UNKNOWN used anywhere in the code?  In any case if the enum should include  UNKNOWN let's make it zero, it's a good practice to assign zero value to a zero concept.

2023-02-03 19:36 UTC, ibrodkin commented on ChronoAPI/ChronoLog/include/RPCVisor.h
> -        if (CHRONOLOG_CONF->IS_SERVER) {
RPCVisor  does know it's own identity , IS_SERVER or IS_VISOR check is redundant

2023-02-03 19:36 UTC, ibrodkin commented on ChronoAPI/ChronoLog/include/RPCFactory.h
>      }
Are we assigning CHRONOLOG_CONF-> RPC_BASE_VISOR_PORT a new value here? I know this code is inherited from hcl, where every RPC instance is both a server and a client , this is not our Visor-Client RPC relationship.  In any case ConfigurationManager contents should not be manipulated by other modules, let's revisit this use case

2023-02-03 19:36 UTC, ibrodkin commented on ChronoAPI/ChronoLog/include/RPCVisor.h
>      }
ClientRegistry, MetadataMaps, etc should be instantiated before any of the RPC communication objects are, no need to check validity of the pointer on every client API call. If we structure our code correctly g_clientRegistryManager == nullptr case would be prevented by the compiler.  Either ClientRegistry::GetInstance() should be called in RPCVisor constructor or the reference to a valid ClientRegistry instance should be passed to RPCVisor constructor.   I think Aparna already started making GetInstance changes on a different branch...

2023-02-03 19:36 UTC, ibrodkin commented on ChronoAPI/ChronoLog/include/ConfigurationManager.h
ClocksourceManager should be part of ConfigurationManager.h
Configuration Manager is only responsible for reading in the configuration values from the JSON formatted file and doing basic validation on them ( valid ip string , etc)
ConfigurationManager should not be instantiating ClocksourceManager.  ConfigurationManager is a Singleton that all other modules will discover through it's GetInstance() function and pull the configuration values they need  from ConfigurationManager.

2023-02-16 17:44 UTC, ibrodkin requested changes
Could you, please, break the JSON object into sections? Something like this:
{process:"chrono_visor" 
     {clock : { clock_type:"TSC" }{..} }
     {client_rpc : {..all rpc parameters}
     { admin_rpc: { rpc parameters for communication with keepers}
     { authentication : { type and location of authentication module}
     { ...}
}

2023-02-23 20:24 UTC, fkengun commented
In commit [https://github.com/scs-lab/ChronoLog/commit/8bf34f2d961d1ea5e402fc95f48e2a55e6d4baf1](url), the configuration file structure is changed as follows:
- Hierarchy is introduced. Related configurations are grouped.
- All ChronoLog components have to use the same configuration file since agreements are required across all of them (e.g. clock source, rpc protocol, etc).
- RPC for communications between each pair of Client, Visor and Keeper are separated. 
- Component-local configurations are left empty for now.
@ibrodkin pls take a look and comment.

2023-02-27 16:46 UTC, ibrodkin commented
Please, merge the most recent develop into your 17 branch and remove "include ClocksourceManager.h"  reference from ConfigurationManager.h  file.

2023-02-27 18:24 UTC, fkengun commented
> 

develop is merged to 17 branch. However, the server cannot launch anymore. Please try it on your side. I will debug it at the same time.

2023-03-01 17:48 UTC, ibrodkin approved these changes
please, merge

2023-03-01 18:08 UTC, merged